# Generated by Django 5.0.2 on 2024-02-12 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='Reflex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(choices=[('week', 'Раз в неделю'), ('every_day', 'Каждый день')], default='every_day', max_length=100, verbose_name='Переодичность')),
                ('ia_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятности')),
                ('fee', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознагрождение')),
                ('time_to_complete', models.PositiveIntegerField(default=1, verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=100, verbose_name='Активность')),
                ('data', models.DateTimeField(verbose_name='Время действия')),
                ('locale', models.CharField(max_length=150, verbose_name='Место действия')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Рефлекс',
                'verbose_name_plural': 'Рефлексы',
            },
        ),
    ]
