# Generated by Django 5.0.2 on 2024-02-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflex',
            old_name='ia_published',
            new_name='is_published',
        ),
    ]
